bindPort = 7000
auth.token = "frp-token-2024"

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin123456"

log.to = "/app/frp/frps.log"
log.level = "info"
log.maxDays = 3

allowPorts = [
  { start = 10000, end = 10100 }
]

transport.maxPoolCount = 5
transport.tcpMux = true
